# Generated by Django 3.2.5 on 2021-07-14 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.FloatField(default=0.0)),
                ('pb', models.FloatField(default=0.0)),
                ('mar_cap', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('financials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.financials')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.prices')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stocks.stock')),
            ],
        ),
    ]
