# Generated by Django 3.2.5 on 2021-07-22 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.FloatField(default=0.0, null=True)),
                ('pb', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('finances', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.financials')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_price', models.FloatField(db_index=True, default=0.0)),
                ('key_data', models.CharField(db_index=True, default='TEST_DATA', max_length=50)),
                ('objects_stocks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
